const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),KEY='tradepilot-trades-v2',PLAN='tradepilot-plan-v1';let trades=JSON.parse(localStorage.getItem(KEY)||'[]');
const euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n)||0),num=n=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(Number(n)||0);
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid'}).format(new Date())}
function save(){localStorage.setItem(KEY,JSON.stringify(trades));renderAll();window.tradePilotRisk?.renderRiskPanel();window.tradePilotAnalytics?.render()}
function go(v){$$('.view').forEach(x=>x.classList.remove('active-view'));$(`#view-${v}`).classList.add('active-view');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#page-title').textContent={dashboard:'Dashboard',market:'Mercados',calculator:'Calculadora',journal:'Diario de trading',stats:'Estadísticas',checklist:'Checklist',settings:'Configuración'}[v]||'Dashboard';if(v==='market')loadMarket();if(v==='stats')window.tradePilotAnalytics?.render()}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function calc(){let c=+$('#calc-capital').value||0,r=+$('#calc-risk').value||0,e=+$('#calc-entry').value||0,s=+$('#calc-stop').value||0,tp=+$('#calc-tp').value||0,side=$('#calc-side').value,risk=c*r/100,dist=e?Math.abs(e-s):0,reward=e?Math.abs(tp-e):0,valid=side==='long'?s<e&&tp>e:s>e&&tp<e,rr=dist?reward/dist:0,size=dist?risk/dist:0,profit=size*reward;$('#r-risk').textContent=euro(risk);$('#r-stop').textContent=e?num(dist/e*100)+'%':'—';$('#r-size').textContent=euro(size);$('#r-profit').textContent=euro(profit);$('#r-rr').textContent=dist?num(rr):'—';let w=$('#calc-warning');w.className='notice '+(valid&&rr>=2?'success':'warning');w.textContent=!valid?'⚠ Los niveles no corresponden con la dirección elegida.':rr>=2?'✓ Configuración con R:R ≥ 1:2':'⚠ R:R inferior a 1:2 — revisa el setup'}
$$('#view-calculator input,#view-calculator select').forEach(x=>x.addEventListener('input',calc));
function tradeTable(a){if(!a.length)return '<div class="empty">Todavía no hay operaciones registradas.</div>';return `<table class="table"><thead><tr><th>Fecha</th><th>Activo</th><th>Dir.</th><th>Entrada</th><th>Salida</th><th>Resultado</th><th>R:R</th><th></th></tr></thead><tbody>${a.map(t=>`<tr><td>${t.date}</td><td><strong>${t.symbol}</strong></td><td>${t.side}</td><td>${t.entry}</td><td>${t.exit}</td><td class="${+t.result>=0?'positive':'negative'}">${euro(+t.result)}</td><td>${t.rr?num(t.rr):'—'}</td><td><button class="text-btn delete-trade" data-id="${t.id}">Eliminar</button></td></tr>`).join('')}</tbody></table>`}
function bindDelete(){$$('.delete-trade').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar esta operación demo?')){trades=trades.filter(t=>t.id!==b.dataset.id);save()}})}
function renderDashboard(){let net=trades.reduce((a,t)=>a+(+t.result||0),0),capital=window.tradePilotRisk?.riskSettings()?.capital||10000,balance=capital+net,closed=trades.filter(t=>t.result!==''),wins=closed.filter(t=>+t.result>0),wr=closed.length?wins.length/closed.length*100:0,rrs=closed.filter(t=>+t.rr>0).map(t=>+t.rr),avg=rrs.length?rrs.reduce((a,b)=>a+b,0)/rrs.length:0;$('#current-balance').textContent=euro(balance);$('#balance-change').textContent=(net>=0?'+':'')+euro(net)+' · '+(net/capital*100||0).toFixed(2).replace('.',',')+'%';$('#balance-change').className='change '+(net>=0?'positive':'negative');$('#trade-count').textContent=trades.length;$('#win-rate').textContent=closed.length?num(wr)+'%':'—';$('#avg-rr').textContent=avg?num(avg):'—';$('#today-count').textContent=trades.filter(t=>t.date===today()).length;let run=0;[...closed].reverse().some(t=>{let p=+t.result>=0?'W':'L';if(!run)run=p==='W'?1:-1;else if((run>0)===(p==='W'))run+=p==='W'?1:-1;else return true;return false});$('#streak').textContent=run?`${Math.abs(run)} ${run>0?'W':'L'}`:'—';$('#recent-trades').innerHTML=tradeTable(trades.slice(-5).reverse());bindDelete();drawChart()}
function renderJournal(){$('#journal-table').innerHTML=tradeTable([...trades].reverse());bindDelete()}
function renderStats(){let gp=trades.filter(t=>+t.result>0).reduce((a,t)=>a+ +t.result,0),gl=Math.abs(trades.filter(t=>+t.result<0).reduce((a,t)=>a+ +t.result,0)),net=gp-gl;$('#gross-profit').textContent=euro(gp);$('#gross-loss').textContent=euro(gl);$('#net-result').textContent=euro(net);$('#net-result').className='metric '+(net>=0?'positive':'negative');$('#profit-factor').textContent=gl?num(gp/gl):'—';$('#stats-insight').textContent=trades.length<10?'Aún no hay suficientes operaciones para evaluar una estrategia con seriedad. Registra al menos 10–20 trades demo.':`Has registrado ${trades.length} operaciones. Tu muestra tiene ${num(trades.filter(t=>+t.result>0).length/trades.length*100)}% de aciertos. Evalúa la muestra completa, no una operación aislada.`}
function drawChart(){let c=$('#equity-chart'),ctx=c.getContext('2d'),w=c.clientWidth,h=c.clientHeight,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!trades.length){$('#chart-empty').style.display='grid';return}$('#chart-empty').style.display='none';let capital=window.tradePilotRisk?.riskSettings()?.capital||10000,vals=[capital],sum=capital;trades.forEach(t=>{sum+=+t.result||0;vals.push(sum)});let min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;ctx.beginPath();vals.forEach((v,i)=>{let x=i*(w/(vals.length-1)),y=h-20-(v-min)/range*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#8da7ff';ctx.lineWidth=2;ctx.stroke()}
function renderChecklist(){let items=['La tendencia está clara','Tengo una zona/estructura definida','Existe confirmación de entrada','El Stop Loss está definido','El riesgo está dentro de mi límite','El R:R es aceptable','Estoy entrando según mi plan, no por impulso'];$('#check-items').innerHTML=items.map((x,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}"> ${x}</label>`).join('');$$('[data-check]').forEach(x=>x.onchange=updateCheck)}function updateCheck(){let n=[...$$('[data-check]')].filter(x=>x.checked).length;$('#check-score').textContent=`${n}/7`;let v=$('#check-verdict'),p=$('#check-text');v.className='verdict '+(n>=6?'good':n>=4?'neutral':'bad');v.textContent=n>=6?'SETUP APTO':n>=4?'REVISAR SETUP':'NO OPERAR';p.textContent=n>=6?'Tienes una estructura razonable. Esto no garantiza beneficio.':n>=4?'Faltan confirmaciones. Espera o mejora el setup.':'Hay demasiadas condiciones sin confirmar. La disciplina también es no entrar.'}$('#clear-check').onclick=()=>{$$('[data-check]').forEach(x=>x.checked=false);updateCheck()};
function renderPlan(){let p=JSON.parse(localStorage.getItem(PLAN)||'{}');if(p.entry)$('#plan-entry').value=p.entry;if(p.sl)$('#plan-sl').value=p.sl;if(p.tp)$('#plan-tp').value=p.tp;if(p.bias)$('#plan-bias').value=p.bias;if(p.thesis)$('#plan-thesis').value=p.thesis}function savePlan(){let p={entry:$('#plan-entry').value,sl:$('#plan-sl').value,tp:$('#plan-tp').value,bias:$('#plan-bias').value,thesis:$('#plan-thesis').value,updated:new Date().toISOString()};localStorage.setItem(PLAN,JSON.stringify(p));$('#plan-saved').textContent=' · Guardado localmente'}
function loadMarket(){renderPlan();if(typeof TradingView==='undefined'){setTimeout(loadMarket,400);return}let box=$('#tradingview_chart');box.innerHTML='';new TradingView.widget({autosize:true,symbol:$('#market-symbol').value,interval:$('#market-timeframe').value,timezone:'Europe/Madrid',theme:'dark',style:'1',locale:'es',enable_publishing:false,hide_top_toolbar:false,hide_legend:false,allow_symbol_change:false,container_id:'tradingview_chart'});$('#open-external-chart').onclick=()=>window.open('https://www.tradingview.com/chart/?symbol='+encodeURIComponent($('#market-symbol').value),'_blank','noopener')}
$('#market-symbol').onchange=loadMarket;$('#market-timeframe').onchange=loadMarket;$('#save-plan').onclick=savePlan;
$('#new-trade-btn').onclick=()=>$('#trade-form-card').classList.remove('hidden');$('#cancel-trade').onclick=()=>$('#trade-form-card').classList.add('hidden');$('#trade-form').onsubmit=e=>{e.preventDefault();let guard=window.tradePilotRisk?.riskGuard();if(guard){alert(guard);return}let t={id:crypto.randomUUID(),date:today(),symbol:$('#trade-symbol').value.trim().toUpperCase(),side:$('#trade-side').value,entry:$('#trade-entry').value,exit:$('#trade-exit').value,sl:$('#trade-sl').value,tp:$('#trade-tp').value,result:$('#trade-result').value,rr:$('#trade-rr').value,notes:$('#trade-notes').value};trades.push(t);e.target.reset();$('#trade-form-card').classList.add('hidden');save();go('journal')};$('#reset-btn').onclick=()=>{if(confirm('¿Borrar todas las operaciones de esta cuenta demo?')){trades=[];save()}};
function renderAll(){renderDashboard();renderJournal();renderStats();renderChecklist();window.tradePilotRisk?.renderRiskPanel();window.tradePilotAnalytics?.render();if($('#view-market')?.classList.contains('active-view'))loadMarket()}renderAll();calc();window.addEventListener('resize',drawChart);
function loadSettingsModule(){if(window.tradePilotSettings)return;const s=document.createElement('script');s.src='./settings.js';s.defer=true;document.body.appendChild(s)}
setTimeout(loadSettingsModule,0);