(()=>{
 const KEY='apex-ledger-backtest-latest-v1';
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function readBacktest(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
 function render(){const host=document.getElementById('automation-center');if(!host||document.getElementById('qualification-panel'))return;const box=document.createElement('div');box.id='qualification-panel';box.className='card';box.innerHTML='<div class="section-head"><div><h3>Cualificación del bot</h3><p>Puertas automáticas de backtest, OOS, regímenes y paper. No implican rentabilidad futura.</p></div><span class="demo-badge">🔒 LIVE BLOQUEADO</span></div><div class="hero-grid" id="qualification-grid"></div><div id="qualification-gates" class="insight"></div><div id="qualification-regimes" class="insight"></div><button id="qualification-refresh" class="ghost-btn">Evaluar puertas de seguridad</button>';host.appendChild(box);document.getElementById('qualification-refresh').onclick=update;update()}
 function update(){const h=window.tradePilotBotHealth?.evaluate?.()||{status:'UNKNOWN',avgProcessScore:0};const p=window.tradePilotPaper?.orders?.()||[],closed=p.filter(x=>x.status==='CLOSED');const b=readBacktest()||{},test=b.test||{},gen=b.generalization||{},reg=b.regimes||{};const violations=Number(window.tradePilotPaper?.violations?.()||0);const g=window.tradePilotGates?.evaluate?.({paperTrades:closed.length,paperViolations:violations,health:h.status,processScore:Number(h.avgProcessScore||0),killSwitch:window.tradePilotKillSwitch?.isArmed?.()||false,backtestTrades:Number(b.sampleSize||0),backtestPF:Number(b.profitFactor||0),backtestExpectancyR:Number(b.expectancyR||0),backtestMaxDD:Number(b.maxDrawdownPct||100),backtestTestTrades:Number(test.count||0),backtestTestPF:Number(test.profitFactor||0),backtestTestExpectancyR:Number(test.expectancyR||0),generalizationRatio:gen.expectancyRatio===null||gen.expectancyRatio===undefined?null:Number(gen.expectancyRatio),regimeWarnings:Array.isArray(b.regimeWarnings)?b.regimeWarnings.length:0});if(!g)return;const grid=document.getElementById('qualification-grid'),list=document.getElementById('qualification-gates'),rp=document.getElementById('qualification-regimes');if(grid)grid.innerHTML='<div class="card"><div class="card-label">ETAPA</div><div class="metric">'+esc(g.stage)+'</div></div><div class="card"><div class="card-label">PUERTAS</div><div class="metric">'+g.passed+'/'+g.total+'</div></div><div class="card"><div class="card-label">PAPER CERRADOS</div><div class="metric">'+closed.length+'</div></div><div class="card"><div class="card-label">BACKTEST</div><div class="metric">'+Number(b.sampleSize||0)+' trades</div></div>';if(list)list.innerHTML=g.gates.map(x=>'<div>'+(x[1]?'✓ ':'✕ ')+esc(x[0])+' — '+esc(x[2])+'</div>').join('');if(rp){const rows=Object.entries(reg);rp.innerHTML='<strong>Regímenes</strong>'+(!rows.length?'<div>Sin análisis de regímenes todavía.</div>':rows.map(([name,x])=>'<div>'+esc(name)+' · '+Number(x.trades||0)+' trades · PF '+(Number.isFinite(Number(x.profitFactor))?Number(x.profitFactor).toFixed(2):'∞')+' · Exp. R '+Number(x.expectancyR||0).toFixed(2)+(x.sampleSufficient?(x.weak?' · ⚠ débil':' · ✓ suficiente'):' · muestra insuficiente')+'</div>').join(''))}}
 function boot(){render()}
 window.tradePilotQualification={render,update};window.addEventListener('apex-paper-updated',update);window.addEventListener('apex-kill-switch',update);window.addEventListener('apex-automation-updated',update);window.addEventListener('apex-backtest-updated',update);window.addEventListener('apex-data-updated',update);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
