const RISK_SETTINGS_KEY='tradepilot-risk-settings-v1';
const defaultRiskSettings={capital:10000,riskPct:1,maxDailyLossPct:3,maxTradesDay:5};
function riskSettings(){try{return {...defaultRiskSettings,...JSON.parse(localStorage.getItem(RISK_SETTINGS_KEY)||'{}')}}catch{return {...defaultRiskSettings}}}
function saveRiskSettings(s){const safe={capital:Math.max(0,Number(s.capital)||0),riskPct:Math.min(10,Math.max(0,Number(s.riskPct)||0)),maxDailyLossPct:Math.min(100,Math.max(0,Number(s.maxDailyLossPct)||0)),maxTradesDay:Math.max(1,Math.round(Number(s.maxTradesDay)||1))};localStorage.setItem(RISK_SETTINGS_KEY,JSON.stringify(safe));renderRiskPanel();window.dispatchEvent(new CustomEvent('risk-updated'))}
function riskTrades(){try{const x=JSON.parse(localStorage.getItem('tradepilot-trades-v2')||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function todayISO(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid'}).format(new Date())}
function riskStatus(){const s=riskSettings(),ts=riskTrades().filter(t=>t.date===todayISO()),daily=ts.reduce((a,t)=>a+(Number(t.result)||0),0),lossLimit=-(s.capital*s.maxDailyLossPct/100);return {settings:s,tradesToday:ts.length,dailyResult:daily,lossLimit,blocked:ts.length>=s.maxTradesDay||daily<=lossLimit}}
function preflightOrder(o={}){const s=riskSettings(),side=o.side,entry=Number(o.entry),stop=Number(o.stop),target=Number(o.target),units=Number(o.units||0);const reasons=[];if(!['LONG','SHORT'].includes(side))reasons.push('Dirección inválida');if(![entry,stop,target].every(Number.isFinite))reasons.push('Niveles inválidos');if(units<0||!Number.isFinite(units))reasons.push('Tamaño inválido');if([entry,stop,target].every(Number.isFinite)){const ok=side==='LONG'?stop<entry&&target>entry:stop>entry&&target<entry;if(!ok)reasons.push('SL/TP incompatibles')}const riskAmount=Number.isFinite(entry)&&Number.isFinite(stop)&&Number.isFinite(units)?Math.abs(entry-stop)*units:null;const maxRisk=s.capital*s.riskPct/100;if(riskAmount!==null&&riskAmount>maxRisk+1e-9)reasons.push('Riesgo por operación excedido');const st=riskStatus();if(st.blocked)reasons.push(riskGuard());const ks=window.tradePilotKillSwitch?.isArmed?.()||window.tradePilotAutomation?.status?.().killSwitch;if(ks)reasons.push('KILL SWITCH ARMADO');return {allowed:reasons.length===0,reasons,riskAmount,maxRisk,status:st}}
function renderRiskPanel(){const host=document.querySelector('#risk-panel');if(!host)return;const s=riskSettings(),st=riskStatus();host.innerHTML=`<div class="section-head"><div><h2>Gestión de riesgo</h2><p>Límites de disciplina para tu cuenta demo.</p></div><div class="risk-state ${st.blocked?'blocked':'ok'}">${st.blocked?'⛔ BLOQUEADO':'● DENTRO DE LÍMITES'}</div></div><div class="form-grid"><label>Capital base (€)<input id="risk-capital" type="number" min="0" step="100" value="${s.capital}"></label><label>Riesgo por operación (%)<input id="risk-pct" type="number" min="0" max="10" step="0.1" value="${s.riskPct}"></label><label>Pérdida máxima diaria (%)<input id="risk-daily" type="number" min="0" max="100" step="0.5" value="${s.maxDailyLossPct}"></label><label>Máx. operaciones/día<input id="risk-max-trades" type="number" min="1" max="100" step="1" value="${s.maxTradesDay}"></label></div><div class="risk-grid"><div><span>Resultado de hoy</span><strong class="${st.dailyResult>=0?'positive':'negative'}">${euro(st.dailyResult)}</strong></div><div><span>Límite de pérdida</span><strong>${euro(st.lossLimit)}</strong></div><div><span>Operaciones hoy</span><strong>${st.tradesToday} / ${s.maxTradesDay}</strong></div></div><button id="save-risk" class="primary-btn">Guardar límites</button><div class="notice ${st.blocked?'warning':'success'}">${st.blocked?'No añadas otra operación demo hasta revisar el límite alcanzado.':'Los límites entrenan disciplina; no garantizan resultados.'}</div>`;document.querySelector('#save-risk').onclick=()=>saveRiskSettings({capital:$('#risk-capital').value,riskPct:$('#risk-pct').value,maxDailyLossPct:$('#risk-daily').value,maxTradesDay:$('#risk-max-trades').value})}
function euro(n){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n)||0)}
function riskGuard(){const st=riskStatus();return st.blocked?`Límite de disciplina alcanzado: ${st.tradesToday}/${st.settings.maxTradesDay} operaciones hoy o pérdida diaria de ${euro(Math.abs(st.lossLimit))}.`:null}
window.tradePilotRisk={riskSettings,saveRiskSettings,riskStatus,riskGuard,preflightOrder,renderRiskPanel};window.addEventListener('load',renderRiskPanel);window.addEventListener('risk-updated',()=>window.dispatchEvent(new Event('resize')));