const RISK_SETTINGS_KEY='tradepilot-risk-settings-v1';
const defaultRiskSettings={capital:10000,riskPct:1,maxDailyLossPct:3,maxTradesDay:5};
function riskSettings(){try{return {...defaultRiskSettings,...JSON.parse(localStorage.getItem(RISK_SETTINGS_KEY)||'{}')}}catch{return {...defaultRiskSettings}}}
function saveRiskSettings(s){localStorage.setItem(RISK_SETTINGS_KEY,JSON.stringify(s));renderRiskPanel()}
function riskTrades(){try{return JSON.parse(localStorage.getItem('tradepilot-trades-v2')||'[]')}catch{return []}}
function todayISO(){return new Date().toISOString().slice(0,10)}
function riskStatus(){const s=riskSettings(),ts=riskTrades().filter(t=>t.date===todayISO()),daily=ts.reduce((a,t)=>a+(Number(t.result)||0),0),lossLimit=-(s.capital*s.maxDailyLossPct/100);return {settings:s,tradesToday:ts.length,dailyResult:daily,lossLimit,blocked:ts.length>=s.maxTradesDay||daily<=lossLimit}}
function renderRiskPanel(){const host=document.querySelector('#risk-panel');if(!host)return;const s=riskSettings(),st=riskStatus();host.innerHTML=`<div class="section-head"><div><h2>Gestión de riesgo</h2><p>Límites de disciplina para tu cuenta demo.</p></div><div class="risk-state ${st.blocked?'blocked':'ok'}">${st.blocked?'⛔ BLOQUEADO':'● DENTRO DE LÍMITES'}</div></div><div class="form-grid"><label>Capital base (€)<input id="risk-capital" type="number" min="0" step="100" value="${s.capital}"></label><label>Riesgo por operación (%)<input id="risk-pct" type="number" min="0" max="10" step="0.1" value="${s.riskPct}"></label><label>Pérdida máxima diaria (%)<input id="risk-daily" type="number" min="0" max="100" step="0.5" value="${s.maxDailyLossPct}"></label><label>Máx. operaciones/día<input id="risk-max-trades" type="number" min="1" max="100" step="1" value="${s.maxTradesDay}"></label></div><div class="risk-grid"><div><span>Resultado de hoy</span><strong class="${st.dailyResult>=0?'positive':'negative'}">${euro(st.dailyResult)}</strong></div><div><span>Límite de pérdida</span><strong>${euro(st.lossLimit)}</strong></div><div><span>Operaciones hoy</span><strong>${st.tradesToday} / ${s.maxTradesDay}</strong></div></div><button id="save-risk" class="primary-btn">Guardar límites</button><div class="notice ${st.blocked?'warning':'success'}">${st.blocked?'No añadas otra operación demo hasta revisar el límite alcanzado.':'Los límites están pensados para practicar disciplina, no garantizan resultados.'}</div>`;document.querySelector('#save-risk').onclick=()=>{saveRiskSettings({capital:+$('#risk-capital').value||0,riskPct:+$('#risk-pct').value||0,maxDailyLossPct:+$('#risk-daily').value||0,maxTradesDay:Math.max(1,+$('#risk-max-trades').value||1)})}}
function euro(n){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n)||0)}
function mountRiskPanel(){const calc=document.querySelector('#view-calculator');if(!calc||document.querySelector('#risk-panel'))return;const d=document.createElement('div');d.id='risk-panel';d.className='card';d.style.marginTop='14px';calc.appendChild(d);renderRiskPanel()}
function riskGuard(){const st=riskStatus();return st.blocked?`Límite de disciplina alcanzado: ${st.tradesToday}/${st.settings.maxTradesDay} operaciones hoy o pérdida diaria de ${euro(Math.abs(st.lossLimit))}.`:null}
window.tradePilotRisk={riskSettings,riskStatus,riskGuard,renderRiskPanel,mountRiskPanel};window.addEventListener('load',mountRiskPanel);setInterval(()=>{if(document.querySelector('#view-calculator')?.classList.contains('active-view'))renderRiskPanel()},5000);