(()=>{
  const $=s=>document.querySelector(s),KEY='tradepilot-trades-v2';
  const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
  const closed=()=>read().filter(t=>String(t.result??'').trim()!==''&&Number.isFinite(Number(t.result)));
  const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(v)||0);
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function analyse(){
    const a=closed(),n=a.length;if(!n)return {score:0,grade:'SIN DATOS',reasons:['Registra operaciones cerradas para activar el análisis.'],patterns:[],overtrade:null,recovery:null};
    const wins=a.filter(t=>+t.result>0),wr=wins.length/n,rrs=a.filter(t=>+t.rr>0).map(t=>+t.rr),avgR=rrs.length?rrs.reduce((s,v)=>s+v,0)/rrs.length:0;
    const s=window.tradePilotRisk?.riskStatus?.(),today=a.filter(t=>t.date===new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid'}).format(new Date())).length,limit=s?.settings?.maxTradesDay||5;
    const quality=window.tradePilotScoring?.score?Math.round(a.reduce((sum,t)=>sum+window.tradePilotScoring.score(t,a).score,0)/n):50;
    let score=quality;if(n>=20)score+=5;if(today>=limit)score-=15;score=Math.max(0,Math.min(100,Math.round(score)));
    const reasons=[];if(wr>=.55)reasons.push('La muestra tiene una tasa de acierto alta; comprueba que no dependa de pocas operaciones.');else if(wr<.4)reasons.push('Tasa de acierto baja: revisa entradas, invalidaciones y selección de setups.');if(avgR>=1.5)reasons.push('El R:R medio registrado es saludable.');else if(avgR>0)reasons.push('El R:R medio es ajustado: revisa la relación entre riesgo y objetivo.');if(n<20)reasons.push('Muestra pequeña: no saques conclusiones definitivas todavía.');
    const patterns=[];const by=(k)=>{const m={};a.forEach(t=>{const v=String(t[k]||'').trim();if(v)(m[v]??=[]).push(+t.result)});return Object.entries(m).map(([k,v])=>({k,n:v.length,net:v.reduce((x,y)=>x+y,0),wr:v.filter(x=>x>0).length/v.length})).sort((x,y)=>y.net-x.net)};
    const strategies=by('strategy').filter(x=>x.n>=3),sessions=by('session').filter(x=>x.n>=3);if(strategies.length){const best=strategies[0],worst=strategies[strategies.length-1];if(best.net>0)patterns.push(`Mejor patrón con muestra mínima: ${best.k}, ${money(best.net)} en ${best.n} trades.`);if(worst!==best&&worst.net<0)patterns.push(`Patrón a revisar: ${worst.k} acumula ${money(worst.net)}.`)}if(sessions.length&&sessions[0].net>0)patterns.push(`Sesión más fuerte con ≥3 trades: ${sessions[0].k}, ${money(sessions[0].net)}.`);
    const dd=(()=>{let eq=0,peak=0,max=0;a.forEach(t=>{eq+=+t.result;peak=Math.max(peak,eq);max=Math.max(max,peak-eq)});return max})();const net=a.reduce((s,t)=>s+ +t.result,0);const recovery=dd&&net?net/dd:null;
    return {score,grade:score>=80?'DISCIPLINADO':score>=65?'SÓLIDO':score>=50?'EN DESARROLLO':'REVISAR',reasons,patterns,overtrade:{today,limit,pct:limit?today/limit*100:0},recovery:dd?{dd,net,recovery}:null};
  }
  function render(){const host=$('#view-dashboard');if(!host||$('#trader-insights'))return;const c=document.createElement('div');c.id='trader-insights';c.className='card';c.innerHTML='<div class="section-head"><div><h2>Coach de proceso</h2><p>Indicadores para mejorar tu comportamiento y registro, no para predecir beneficios.</p></div></div><div class="hero-grid" id="insight-grid"></div><div class="two-col"><div><h3>Patrones detectados</h3><div id="insight-patterns" class="insight"></div></div><div><h3>Alertas de disciplina</h3><div id="insight-alerts" class="insight"></div></div></div>';const footer=host.querySelector('.app-footer');host.insertBefore(c,footer||null);update()}
  function update(){const c=$('#trader-insights');if(!c)return;const x=analyse();$('#insight-grid').innerHTML=`<div class="card"><div class="card-label">SCORE DE PROCESO</div><div class="metric">${x.score}/100</div><div class="muted">${esc(x.grade)}</div></div><div class="card"><div class="card-label">SOBREOPERACIÓN</div><div class="metric">${x.overtrade?x.overtrade.today+'/'+x.overtrade.limit:'—'}</div><div class="muted">operaciones de hoy</div></div><div class="card"><div class="card-label">RECUPERACIÓN</div><div class="metric">${x.recovery?.recovery!==null&&x.recovery?.recovery!==undefined?x.recovery.recovery.toFixed(2)+'×':'—'}</div><div class="muted">neto / drawdown</div></div>`;$('#insight-patterns').innerHTML=(x.patterns.length?x.patterns:x.reasons).map(v=>`<div>• ${esc(v)}</div>`).join('');const alerts=[];if(x.overtrade&&x.overtrade.pct>=80)alerts.push(x.overtrade.pct>=100?'⚠ Límite diario alcanzado. No registres otra entrada.':'⚠ Estás cerca del límite diario de operaciones.');if(x.recovery?.dd>0&&x.recovery.net<0)alerts.push('⚠ La curva sigue bajo drawdown: prioriza revisar el proceso.');if(!alerts.length)alerts.push('✓ No se detecta una alerta de disciplina con los datos actuales.');$('#insight-alerts').innerHTML=alerts.map(v=>`<div>${esc(v)}</div>`).join('')}
  function init(){render();update()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.addEventListener('load',init);window.addEventListener('risk-updated',update);window.addEventListener('apex-data-updated',update);
})();
